# node js app to run on port 8080

version: '3.9'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        PACKAGES: "nano wget curl"
    container_name: connet-web
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=mongodb
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
      - NODE_ENV=production
      - APP_VERSION=1.0
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www/
      - node_modules:/var/www/node_modules
    depends_on:
      - mongodb
      # - node_modules:/home/node/app/node_modules
    # command: ./wait-for.sh mongodb:27017 -- /node_modules/.bin/nodemon app.js
    networks:
      - connet-network

  # mongo db to run on port 27017

  mongodb:
    image: mongo:4.2.8
    container_name: connet-db
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    # volumes:  
    #   - dbdata:/data/db
    networks:
      - connet-network
    # ports:
    #   - "27017:27017"

networks:
  connet-network:
    driver: bridge

volumes:
  # dbdata:
  node_modules:  
