# node js app to run on port 3000

version: '3.9'

services:
  # web:
  #   build: .
  #   # image: node:8.16.0
  #   container_name: connet-web
  #   restart: unless-stopped
  #   env_file: .env
  #   environment:
  #     - MONGO_USERNAME=$MONGO_USERNAME
  #     - MONGO_PASSWORD=$MONGO_PASSWORD
  #     - MONGO_HOSTNAME=$MONGO_HOSTNAME
  #     - MONGO_PORT=$MONGO_PORT
  #     - MONGO_DB=$MONGO_DB 
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - .:/home/node/app
  #     - node_modules:/home/node/app/node_modules
  #   command: /home/node/app/node_modules/.bin/nodemon app.js
  #   networks:
  #     - connet-network
  #   depends_on:
  #     - mongodb

  # mongo db to run on port 27017

  mongodb:
    image: mongo:4.1.6
    container_name: connet-db
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    # volumes:  
    #   - dbdata:/data/db
    networks:
      - connet-network
    ports:
      - 27017:27017

networks:
  connet-network:
    driver: bridge

# volumes:
#   dbdata:
#   node_modules:  
